"""Checks every data module against the extracted vanilla data and the pinned compiler."""

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

import gen_parts
import gen_settlement
import merge_preview

# Each generator takes a spec and returns {relative path: file text}; a module's files must match all of them.
GENERATORS = [gen_parts.build, gen_settlement.build]

REPO = Path(__file__).resolve().parent.parent
SPECS = REPO / "specs"
MODS = REPO / "mod"
EXTRACTED = merge_preview.EXTRACTED
ALL_FILES = REPO / "scratch" / "all_files.txt"

# Every folder under mod/ is a module; a spec under specs/ is optional (hand-written modules have none).
MODULES = sorted(p.name for p in MODS.iterdir() if p.is_dir())
SPEC_MODULES = [m for m in MODULES if (SPECS / f"{m}.json").is_file()]

pytestmark = pytest.mark.skipif(
    not (EXTRACTED / "metadata/reality/tables/basebuildingobjectstable.MXML").is_file()
    or not merge_preview.MBIN.is_file()
    or not ALL_FILES.is_file(),
    reason="run tools/bootstrap.ps1 and tools/extract.py first",
)


def spec_of(module):
    path = SPECS / f"{module}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


def test_every_spec_has_a_module():
    for spec in SPECS.glob("*.json"):
        assert (MODS / spec.stem).is_dir(), f"{spec.name} has no mod/{spec.stem} folder"


@pytest.fixture(scope="module")
def game_files():
    names = set()
    for line in ALL_FILES.read_text(encoding="utf-8", errors="replace").splitlines():
        names.add(line.strip().lower())
    return names


@pytest.fixture(scope="module")
def vanilla_loc_keys():
    keys = set()
    for f in (EXTRACTED / "language").glob("*english.MXML"):
        keys.update(re.findall(r'TkLocalisationEntry" _id="([^"]+)"', f.read_text(encoding="utf-8")))
    return keys


@pytest.fixture(scope="module")
def vanilla_cost_ids():
    root = ET.parse(EXTRACTED / "metadata/reality/tables/basebuildingcoststable.MXML").getroot()
    return {e.get("_id") for e in root.find("Property[@name='ObjectCosts']")}


def module_loc_keys(module):
    keys = set(spec_of(module).get("text", {}))
    for f in (MODS / module).rglob("*.EXML"):
        if f.parent.name.upper() == "LANGUAGE":
            keys.update(re.findall(r'_id="([^"]+)"', f.read_text(encoding="utf-8")))
    return keys


def generated_files(spec):
    merged = {}
    for build in GENERATORS:
        for rel, text in build(spec).items():
            assert rel not in merged, f"{rel} is generated by two generators"
            merged[rel] = text
    return merged


def test_two_generators_may_not_write_the_same_file(monkeypatch):
    monkeypatch.setattr(sys.modules[__name__], "GENERATORS", [gen_parts.build, gen_parts.build])
    with pytest.raises(AssertionError, match="two generators"):
        generated_files({"text": {"OT_X": "x"}})


@pytest.mark.parametrize("module", SPEC_MODULES)
def test_generated_files_match_the_spec(module):
    for rel, text in generated_files(spec_of(module)).items():
        path = MODS / module / rel
        assert path.is_file(), f"{rel} is missing; rerun the generators in tools/"
        assert path.read_text(encoding="utf-8") == text, f"{rel} is stale; rerun the generators in tools/"


@pytest.mark.parametrize("module", MODULES)
def test_every_patch_merges_and_compiles(module, tmp_path):
    results = merge_preview.preview_module(MODS / module, tmp_path)
    assert results, f"{module} has no patches"
    failures = [f"{r.patch.name}: {r.message}" for r in results if not r.ok]
    assert not failures


@pytest.mark.parametrize("module", SPEC_MODULES)
def test_new_parts_are_complete(module, game_files, vanilla_loc_keys, vanilla_cost_ids):
    spec = spec_of(module)
    out = {str(k).replace("\\", "/"): ET.fromstring(v) for k, v in gen_parts.build(spec).items()}
    objects = out.get("METADATA/REALITY/TABLES/BASEBUILDINGOBJECTSTABLE.EXML")
    costs = out.get("METADATA/REALITY/TABLES/BASEBUILDINGCOSTSTABLE.EXML")
    products = out.get("METADATA/REALITY/TABLES/NMS_BASEPARTPRODUCTS.EXML")
    known_text = vanilla_loc_keys | module_loc_keys(module)
    for part in spec.get("parts", []):
        id_ = part["id"]
        assert id_.startswith("OT_"), id_
        entry = objects.find(f"Property[@name='Objects']/Property[@_id='{id_}']")
        scene = entry.find("Property[@name='PlacementScene']/Property[@name='Filename']").get("value")
        assert scene.lower() in game_files, f"{id_}: scene {scene} is not in the game files"
        groups = entry.find("Property[@name='Groups']")
        assert len(groups) > 0, f"{id_} has no build-menu group"
        # Most vanilla parts have no cost entry; a new part has one exactly when its source does.
        has_cost = costs is not None and costs.find(f"Property[@name='ObjectCosts']/Property[@_id='{id_}']") is not None
        assert has_cost == (part["copy_from"] in vanilla_cost_ids), f"{id_}: cost entry should mirror {part['copy_from']}"
        product = products.find(f"Property[@name='Table']/Property[@_id='{id_}']")
        assert product is not None, f"{id_} has no product"
        for field in ("Name", "NameLower", "Description"):
            key = product.find(f"Property[@name='{field}']").get("value")
            assert key in known_text, f"{id_}.{field}: no text for {key}"


def test_ids_are_unique_across_modules():
    ids = {}
    for spec_file in SPECS.glob("*.json"):
        spec = json.loads(spec_file.read_text(encoding="utf-8"))
        for item in spec.get("parts", []):
            assert item["id"] not in ids, f"{item['id']} defined in {ids.get(item['id'])} and {spec_file.stem}"
            ids[item["id"]] = spec_file.stem


def test_compatibility_file_is_current():
    import compat_report

    expected = compat_report.generate_compatibility(MODS, EXTRACTED)
    on_disk = (REPO / "COMPATIBILITY.md").read_text(encoding="utf-8")
    assert on_disk == expected, "COMPATIBILITY.md is stale; rerun tools/compat_report.py"
