"""List what the shipped modules change in vanilla data, and find installed mods that touch the same data.

  compat_report.py                     regenerate COMPATIBILITY.md from the patches under mod/
  compat_report.py --mods <MODS dir>   scan an installed MODS folder read-only and report overlaps

A scan never writes COMPATIBILITY.md: a player's mod list is personal, so the
scan goes to --out or stdout. Scanning refuses while the game runs.
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

import merge_preview
import nmsenv
from merge_preview import PatchError, vanilla_relpath

REPO = Path(__file__).resolve().parent.parent
EXCLUDED_MODULES = ("OverseersToolkit-Probes", "OverseersToolkit-TestTuning")
DEV_PREFIX = "_OTDEV_"
PATCH_SUFFIXES = (".EXML", ".MXML", ".MBIN")


class CompatError(Exception):
    pass


@dataclass(frozen=True)
class Finding:
    mod: str
    file: str
    kind: str  # conflict, note, shared-file, may-not-load, unreadable
    message: str


@dataclass(frozen=True)
class Edit:
    file: str  # mod-relative patch path, POSIX
    path: str
    kind: str  # changed, list-append, added, overwritten
    old: str = ""
    new: str = ""


# --- reading patches ---------------------------------------------------------


def load_game_files(path):
    """Lower-case pak paths from an hgpaktool listing, skipping its "Listing ..." headers."""
    names = set()
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if line and not line.startswith("Listing "):
            names.add(line.lower())
    return names


def _target(rel):
    """Lower-case vanilla MXML path a mod file patches, as a comparable key."""
    return vanilla_relpath(Path(rel)).as_posix().lower()


def _classify(record, rel):
    kind = record["kind"]
    if kind == "unchanged":
        return None
    if kind == "added" and record["path"].endswith("[+]"):
        return Edit(rel, record["path"][: -len("[+]")], "list-append")
    if kind == "changed":
        return Edit(rel, record["path"], "changed", record.get("old") or "", record.get("new") or "")
    return Edit(rel, record["path"], kind)


def patch_edits(patch_path, rel, vanilla_dir):
    """Edits one EXML patch makes against vanilla. Raises PatchError or ET.ParseError."""
    vanilla_path = Path(vanilla_dir) / vanilla_relpath(Path(rel))
    if not vanilla_path.is_file():
        raise PatchError(f"no vanilla file for {rel}")
    _, records = merge_preview.merge(ET.parse(vanilla_path).getroot(), ET.parse(patch_path).getroot())
    return [e for e in (_classify(r, rel) for r in records) if e is not None]


def _modules(mod_root, include_test_modules):
    mod_root = Path(mod_root)
    if not mod_root.is_dir():
        return []
    names = sorted(p.name for p in mod_root.iterdir() if p.is_dir())
    return [n for n in names if include_test_modules or n not in EXCLUDED_MODULES]


def _patch_files(folder):
    folder = Path(folder)
    for p in sorted(folder.rglob("*")):
        if p.is_file() and p.suffix.upper() in PATCH_SUFFIXES:
            yield p, p.relative_to(folder).as_posix()


def module_edits(mod_root, vanilla_dir, include_test_modules=False):
    """{module: (edits, new whole files)} for our modules. A patch that fails to merge is an error."""
    result = {}
    for name in _modules(mod_root, include_test_modules):
        edits, whole = [], []
        for path, rel in _patch_files(Path(mod_root) / name):
            if path.suffix.upper() != ".EXML":
                whole.append(rel)
                continue
            try:
                edits.extend(patch_edits(path, rel, vanilla_dir))
            except (PatchError, ET.ParseError) as e:
                raise CompatError(f"{name}/{rel}: {e}") from e
        result[name] = (edits, whole)
    return result


# --- COMPATIBILITY.md --------------------------------------------------------


def _cell(value):
    return str(value).replace("|", "\\|")


def _table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return lines


def generate_compatibility(mod_root, vanilla_dir, include_test_modules=False):
    modules = module_edits(mod_root, vanilla_dir, include_test_modules)
    out = [
        "# Compatibility",
        "",
        "Generated by `tools/compat_report.py` from the patches under mod/. Do not edit by hand.",
        "",
        "Each module lists the vanilla entries and fields it changes, then what it adds. "
        "Another mod that changes the same field conflicts; one that appends to the same list does not.",
        "",
    ]
    if not modules:
        out += ["No shipped modules yet.", ""]
    for name, (edits, whole) in modules.items():
        changed = sorted((e.file, e.path, e.old, e.new) for e in edits if e.kind == "changed")
        appended = sorted({(e.file, e.path) for e in edits if e.kind == "list-append"})
        replaced = sorted({(e.file, e.path) for e in edits if e.kind == "overwritten"})
        added = sorted({(e.file, e.path) for e in edits if e.kind == "added"})
        out += [f"## {name}", "", "### Edits vanilla", ""]
        if not (changed or appended or replaced):
            out += ["This module does not edit vanilla entries.", ""]
        if changed:
            out += _table(["File", "Field", "Vanilla", "Ours"], changed) + [""]
        if appended:
            out += ["Appends to these vanilla lists:", ""] + _table(["File", "List"], appended) + [""]
        if replaced:
            out += ["Replaces these vanilla lists outright:", ""] + _table(["File", "List"], replaced) + [""]
        out += ["### Adds new", ""]
        rows = added + [(f, "(whole file)") for f in sorted(whole)]
        out += (_table(["File", "Entry"], rows) if rows else ["Nothing new."]) + [""]
    return "\n".join(out).rstrip("\n") + "\n"


# --- scanning an installed MODS folder ---------------------------------------


def _pak_path(rel):
    return vanilla_relpath(Path(rel)).with_suffix(".mbin").as_posix().lower()


def _is_root_globals(rel):
    """A globals patch placed beside the mod's top-level folders instead of under GLOBALS/."""
    path = Path(rel)
    return len(path.parts) == 1 and "GLOBALS" in path.name.upper()


def _compare(mod, rel, theirs, ours, findings):
    our_changed = {e.path: e for e in ours if e.kind == "changed"}
    our_added = {e.path for e in ours if e.kind == "added"}
    our_lists = {e.path for e in ours if e.kind == "list-append"}
    our_replaced = {e.path for e in ours if e.kind == "overwritten"}
    before = len(findings)
    for e in theirs:
        if e.kind == "changed" and e.path in our_changed:
            mine = our_changed[e.path]
            findings.append(
                Finding(mod, rel, "conflict",
                        f"{e.path}: vanilla {mine.old}, ours {mine.new}, theirs {e.new}")
            )  # fmt: skip
        elif e.kind == "added" and e.path in our_added:
            findings.append(Finding(mod, rel, "conflict", f"{e.path}: both add an entry with this ID"))
        elif e.kind == "list-append" and e.path in our_lists:
            findings.append(Finding(mod, rel, "note", f"{e.path}: both append to this list"))
        elif e.kind == "overwritten" and any(p == e.path or p.startswith(e.path + ".") or p.startswith(e.path + "[")
                                             for p in our_changed.keys() | our_added | our_lists):
            findings.append(Finding(mod, rel, "conflict", f"{e.path}: they replace a list we edit"))
        elif e.kind in ("changed", "added", "list-append") and any(
            e.path == p or e.path.startswith(p + ".") or e.path.startswith(p + "[") for p in our_replaced
        ):
            findings.append(Finding(mod, rel, "conflict", f"{e.path}: we replace this list"))
    if len(findings) == before:
        findings.append(Finding(mod, rel, "shared-file", "patches the same file; no shared field"))


def scan_mods(mods_dir, mod_root, vanilla_dir, game_files, include_test_modules=False):
    """Findings for every installed mod that overlaps our patches. Reads only."""
    ours = {}
    for edits, _ in module_edits(mod_root, vanilla_dir, include_test_modules).values():
        for e in edits:
            ours.setdefault(_target(e.file), []).append(e)

    findings = []
    for folder in sorted(p for p in Path(mods_dir).iterdir() if p.is_dir()):
        mod = folder.name
        if mod.upper().startswith(DEV_PREFIX):
            continue
        for path, rel in _patch_files(folder):
            suffix = path.suffix.upper()
            if suffix == ".MXML":
                continue  # full new files such as LocTable.MXML patch nothing
            target = _target(rel)
            if suffix == ".MBIN":
                if target in ours:
                    findings.append(Finding(mod, rel, "conflict", "replaces the whole file we patch"))
                continue
            if _is_root_globals(rel):
                findings.append(
                    Finding(mod, rel, "may-not-load", "globals patches load only from <mod>/GLOBALS/")
                )
                continue
            if _pak_path(rel) not in game_files:
                findings.append(
                    Finding(mod, rel, "may-not-load", "no game file at this path, so the game may ignore it")
                )
                continue
            if target not in ours:
                continue
            try:
                theirs = patch_edits(path, rel, vanilla_dir)
            except (PatchError, ET.ParseError) as e:
                findings.append(Finding(mod, rel, "unreadable", str(e)))
                continue
            _compare(mod, rel, theirs, ours[target], findings)
    return sorted(findings, key=lambda f: (f.mod.lower(), f.file.lower(), f.kind, f.message))


def render_scan(findings):
    if not findings:
        return "No overlap with Overseer's Toolkit patches.\n"
    lines = []
    for f in findings:
        lines.append(f"[{f.kind}] {f.mod} / {f.file}: {f.message}")
    text = "\n".join(lines) + "\n"
    return text.encode("ascii", "backslashreplace").decode("ascii")


# --- CLI ---------------------------------------------------------------------


def main(argv=None, process_name="NMS.exe"):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--mods", help="an installed GAMEDATA/MODS folder to scan read-only")
    parser.add_argument("--out", help="write the scan here instead of stdout")
    parser.add_argument("--include-test-modules", action="store_true")
    parser.add_argument("--mod-root", default=str(REPO / "mod"))
    parser.add_argument("--vanilla", default=str(merge_preview.EXTRACTED))
    parser.add_argument("--game-files", default=str(REPO / "scratch" / "all_files.txt"))
    parser.add_argument("--compat-file", default=str(REPO / "COMPATIBILITY.md"))
    args = parser.parse_args(argv)

    try:
        if not args.mods:
            text = generate_compatibility(args.mod_root, args.vanilla, args.include_test_modules)
            Path(args.compat_file).write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {args.compat_file}")
            return 0
        if nmsenv.game_running(process_name):
            print(f"Refused: {process_name} is running. Quit the game first.", file=sys.stderr)
            return 3
        findings = scan_mods(
            args.mods, args.mod_root, args.vanilla, load_game_files(args.game_files), args.include_test_modules
        )
        text = render_scan(findings)
        if args.out:
            Path(args.out).write_text(text, encoding="ascii", newline="\n")
        else:
            sys.stdout.write(text)
        return 0
    except (CompatError, RuntimeError) as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
